apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"2"},"creationTimestamp":"2021-04-16T18:34:13Z","generation":8,"labels":{"app":"apis"},"name":"apis","namespace":"default","resourceVersion":"6038930","selfLink":"/apis/apps/v1/namespaces/default/deployments/apis","uid":"630cca9c-d8fd-482e-b87f-42b1e667f094"},"spec":{"progressDeadlineSeconds":600,"replicas":3,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"apis"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2021-04-25T21:28:28+03:00"},"creationTimestamp":null,"labels":{"app":"apis"}},"spec":{"containers":[{"args":["book.sh"],"command":["/bin/sh"],"image":"gcr.io/google-samples/hello-app:1.0","imagePullPolicy":"IfNotPresent","name":"hello-app","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":3,"conditions":[{"lastTransitionTime":"2021-04-16T18:34:13Z","lastUpdateTime":"2021-04-25T18:28:34Z","message":"ReplicaSet \"apis-6c8bdfbd6\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"lastTransitionTime":"2021-04-25T18:54:10Z","lastUpdateTime":"2021-04-25T18:54:10Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":8,"readyReplicas":3,"replicas":3,"updatedReplicas":3}}
  creationTimestamp: "2021-04-16T18:34:13Z"
  generation: 9
  labels:
    app: apis
  name: apis
  namespace: default
  resourceVersion: "6041645"
  selfLink: /apis/apps/v1/namespaces/default/deployments/apis
  uid: 630cca9c-d8fd-482e-b87f-42b1e667f094
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apis
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2021-04-25T21:28:28+03:00"
      creationTimestamp: null
      labels:
        app: apis
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        imagePullPolicy: IfNotPresent
        name: hello-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2021-04-25T18:54:10Z"
    lastUpdateTime: "2021-04-25T18:54:10Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-16T18:34:13Z"
    lastUpdateTime: "2021-04-25T19:00:25Z"
    message: ReplicaSet "apis-5ccf768fc4" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 9
  readyReplicas: 3
  replicas: 4
  unavailableReplicas: 1
  updatedReplicas: 1
