terraform {
	backend "remote" {
		organization = "zeromano" # org name from step 2.
		workspaces {
			name = "monkeypesa" # name for your app's state.
		}
	}
}

module "dev_cluster" {
  source        = "./cluster"
  cluster_name  = "dev"
  instance_type = "t2.micro"
  
}

# module "staging_cluster" {
#   source        = "./cluster"
#   cluster_name  = "staging"
#   instance_type = "t2.micro"
# }

# module "production_cluster" {
#   source        = "./cluster"
#   cluster_name  = "production"
#   instance_type = "m5.large"
# }

locals {
   cluster_id = module.dev_cluster.cluster_id

}

output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.dev_cluster.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.dev_cluster.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.dev_cluster.cluster_security_group_id
}

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = module.eks.kubeconfig
# }

# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.eks.config_map_aws_auth
# }


output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = module.dev_cluster.cluster_name
}

# VPC
output "vpc_id" {
  description = "The ID of the VPC"
  value       = module.dev_cluster.vpc_id
}

# Subnets
output "private_subnets" {
  description = "List of IDs of private subnets"
  value       = module.dev_cluster.private_subnets
}

output "public_subnets" {
  description = "List of IDs of public subnets"
  value       = module.dev_cluster.public_subnets
}

# NAT gateways
output "nat_public_ips" {
  description = "List of public Elastic IPs created for AWS NAT Gateway"
  value       = module.dev_cluster.nat_public_ips
}

#RDS
output "db_instance_id" {
    description = "database instance id"
    value = module.dev_cluster.db_instance_id
}

output "db_instance_host_address" {
  description = "rds db host instance address"
  value = module.dev_cluster.db_instance_address
}

output "db_instance_host_endpoint" {
  description = "rds db host instance endpoint"
  value = module.dev_cluster.db_instance_host_endpoint
}